version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: amun
      POSTGRES_PASSWORD: Aashri2017
      POSTGRES_DB: nest
    networks:
      - test
networks:
  test: